error: added MPD_ERROR_MALFORMED
When libmpdclient received a malformed response, it would set error to
"1" instead of using a proper enum value.  This patch adds a new error
code for this case.