error: added MPD_ERROR_STATE
Another enum value for a former "1" error code: MPD_ERROR_STATE is
returned whenever a client attempts to call a function which is
illegal for the current connection state.