error: added MPD_ERROR_OOM
Having a special code for "Out of memory" will come handy, because
libmpdclient cannot generate useful error messages without some
memory.