meson.build: switch to C11
Newer glibc versions require C11, or else (with glibc 2.43):

 ../../src/sticker.c:137:7: error: '_Generic' is a C11 extension [-Werror,-Wc11-extensions]
   137 |         eq = strchr(input, '=');
       |              ^
 /usr/include/string.h:265:3: note: expanded from macro 'strchr'
   265 |   __glibc_const_generic (S, const char *, strchr (S, C))
       |   ^
 /usr/include/aarch64-linux-gnu/sys/cdefs.h:838:3: note: expanded from macro '__glibc_const_generic'
   838 |   _Generic (0 ? (PTR) : (void *) 1,                     \
       |   ^

And since it's been 15 years already... everybody should be fine.